### PR TITLE
fix not linking to dbus

### PR DESCRIPTION
**Pull request by Deminder**
I have been wondering why this did not cause problems before but `dbus` is not linked in the shared library.
#4 is also happening now for me (new mpv version). 

```
[mpv_inhibit_gnome] C plugin error: '/app/etc/mpv/scripts/mpv_inhibit_gnome.so: undefined symbol: dbus_bus_get'
[mpv_inhibit_gnome] Could not load SO plugin /app/etc/mpv/scripts/mpv_inhibit_gnome.so
```

### CODE REVIEW

**Comment by Erick555** [comment]
It would be nice if makefile honored `CFLAGS`/`LDFLAGS` env variables. Currently it unconditionally adds `-g` and doesn't use any compiler/linker optimization

**Comment by Deminder** [comment]
@Erick555 what do you think of building with meson, instead?
https://github.com/Deminder/mpv_inhibit_gnome/blob/meson-build/meson.build

**Comment by Erick555** [comment]
Well, it depends on what is upstream preference. BTW: why prefix=/etc?

**Comment by Deminder** [comment]
> why prefix=/etc?

For a default (non-flatpak) system-wide install.
`./install.sh flatpak` installs to flatpak config dir https://github.com/Deminder/mpv_inhibit_gnome/blob/meson-build/install.sh

**Comment by Guldoman** [comment]
Nice work, LGTM. I'll tag a new release with this fix in a few hours.

> It would be nice if makefile honored `CFLAGS`/`LDFLAGS` env variables. Currently it unconditionally adds `-g` and doesn't use any compiler/linker optimization

What should it look like?
Would simply doing
```Makefile
CFLAGS += $(shell pkg-config --libs --cflags dbus-1)
```
be enough?
Or should we also change the compilation commands to also use `LDFLAGS`?

**Comment by Erick555** [comment]
> For a default (non-flatpak) system-wide install.

The project [README](https://github.com/Deminder/mpv_inhibit_gnome#manually-building-and-installing) says system-wide install path is `/usr/share/mpv/scripts`.


@Guldoman
> What should it look like? Would simply doing
> 
> ```makefile
> CFLAGS += $(shell pkg-config --libs --cflags dbus-1)
> ```

Yeah, it should work like that


> be enough? Or should we also change the compilation commands to also use `LDFLAGS`?

Maybe like below:

`CFLAGS += $(shell pkg-config --cflags dbus-1)`
`LDFLAGS += $(shell pkg-config --libs dbus-1)`

then:
`gcc $(CFLAGS) $(LDFLAGS) ...`

**Comment by Guldoman** [comment]
Would you mind opening a PR with your suggestions? Otherwise I'll do that myself in a few days.

**Comment by Erick555** [comment]
I'm pretty busy right now so It's possible that I wouldn't find the time before you do :smile:

**Comment by Guldoman** [comment]
No worries!

**Pull request merged**
